project:
  type: book

book:
  title: "Variables Aleatorias Continuas"
  author: "Licenciatura en Economía Industrial"
  chapters:
    - index.qmd
    - unif_continua.qmd
    - exponencial.qmd
    - gamma.qmd
    - beta.qmd
    - normal.qmd
    - binomial_negativa.qmd
    - poisson.qmd
    - TCL.qmd
    - geometrica.qmd
    - bernoulli_binomial.qmd
    - uniforme_discreta.qmd
   
bibliography: references.bib

format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 250px
      body-width: 950px
      margin-width: 250px
      gutter-width: 1.5rem
    code-fold: true
    fig-width: 8
    fig-height: 6
    fig-align: "center"

  



